<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<script type="text/javascript" src="../sh_main.js"></script>
<script type="text/javascript" src="../sh_cpp.js"></script>
<!--[IF IE]>
	<script type="text/javascript" src="ierange.js"></script>
<![ENDIF]-->
<script type="text/javascript" src="../masha.min.js"></script>
<script type="text/javascript" src="../all_pack.js"></script>
<link rel="stylesheet" type="text/css" href="../css/masha.css">
<link rel="stylesheet" type="text/css" href="../sh_print.css">
<link rel="stylesheet" type="text/css" href="../toc.css">
<link rel="stylesheet" type="text/css" href="../styles.css">
<script type="text/javascript" src="../page.js"></script>

<title>The std::terminate() function</title>
</head>
<body>
<h3>
<dfn class="label">[except.terminate]</dfn><object type="application/x-oleobject" classid="clsid:1e2a7bd0-dab9-11d0-b93a-00c04fc99f9e"><param name="Keyword" value="[except.terminate]"></object>15.5.1 The <code class="sh_cpp">std::terminate()</code> function </h3>

<p><a class="anchor" id="p1" href="#p1">1</a>In some situations exception handling must be abandoned for less subtle error handling techniques.</p>

<div class="note">
<p>[ <em>Note:</em> These situations are:</p>

<ul>
<li>when the exception handling mechanism, after completing the initialization of the exception object but before
	activation of a handler for the exception (<a title="except.throw" href="except.throw.html">15.1</a>), calls a function that exits via an exception, or</li>
<li>when the exception handling mechanism cannot find a handler for a thrown exception (<a title="except.handle" href="except.handle.html">15.3</a>), or</li>
<li>when the search for a handler (<a title="except.handle" href="except.handle.html">15.3</a>) encounters the outermost block of a function with a
	<i class="nonterminal">noexcept-specification</i> that does not allow the exception (<a title="except.spec" href="except.spec.html">15.4</a>), or</li>
<li>when the destruction of an object during stack unwinding (<a title="except.ctor" href="except.ctor.html">15.2</a>) terminates by throwing an exception,
	or</li>
<li>when initialization of a non-local variable with static or thread storage duration (<a title="basic.start.init" href="basic.start.init.html">3.6.2</a>) exits via an
	exception, or</li>
<li>when destruction of an object with static or thread storage duration exits via an exception (<a title="basic.start.term" href="basic.start.term.html">3.6.3</a>),
	or</li>
<li>when execution of a function registered with <code class="sh_cpp">std::atexit</code> or <code class="sh_cpp">std::at_quick_exit</code> exits via
	an exception (<a title="support.start.term" href="support.start.term.html">18.5</a>), or</li>
<li>when a <i class="nonterminal">throw-expression</i> with no operand attempts to rethrow an exception and no exception is being handled
	(<a title="except.throw" href="except.throw.html">15.1</a>), or</li>
<li>when <code class="sh_cpp">std::unexpected</code> throws an exception which is not allowed by the previously violated
	<i class="nonterminal">dynamic-exception-specification</i>, and <code class="sh_cpp">std::bad_exception</code> is not included in that
	<i class="nonterminal">dynamic-exception-specification</i> (<a title="except.unexpected" href="except.unexpected.html">15.5.2</a>), or</li>
<li>when the implementation’s default unexpected exception handler is called (<a title="unexpected.handler" href="unexpected.handler.html">D.11.1</a>), or</li>
<li>when the function <code class="sh_cpp">std::nested_exception::rethrow_nested</code> is called for an object that has captured no
	exception (<a title="except.nested" href="except.nested.html">18.8.6</a>), or</li>
<li>when execution of the initial function of a thread exits via an exception (<a title="thread.thread.constr" href="thread.thread.constr.html">30.3.1.2</a>), or</li>
<li>when the destructor or the copy assignment operator is invoked on an object of type <code class="sh_cpp">std::thread</code> that
	refers to a joinable thread (<a title="thread.thread.destr" href="thread.thread.destr.html">30.3.1.3</a>, <a title="thread.thread.assign" href="thread.thread.assign.html">30.3.1.4</a>).</li>
</ul>
<p> — <em>end note</em> ]</p>
</div>

<p><a class="anchor" id="p2" href="#p2">2</a>In such cases, <code class="sh_cpp">std::terminate()</code> is called (<a title="exception.terminate" href="terminate.handler.html">18.8.3</a>). In the situation where no matching
handler is found, it is implementation-defined whether or not the stack is unwound before <code class="sh_cpp">std::terminate()</code>
is called. In the situation where the search for a handler (<a title="except.handle" href="except.handle.html">15.3</a>) encounters the outermost block of a
function with a <i class="nonterminal">noexcept-specification</i> that does not allow the exception (<a title="except.spec" href="except.spec.html">15.4</a>), it is
implementation-defined whether the stack is unwound, unwound partially, or not unwound at all before
<code class="sh_cpp">std::terminate()</code> is called. In all other situations, the stack shall not be unwound before
<code class="sh_cpp">std::terminate()</code> is called. An implementation is not permitted to finish stack unwinding prematurely based
on a determination that the unwind process will eventually cause a call to <code class="sh_cpp">std::terminate()</code>.</p>
</body>
</html>



